import { WithCode } from "./sync";


export const generateConstants = (icons: WithCode[]): string => {
    const exports = icons.map(c => `export const ${c.code} = '${c.content}';`).join("\n")
    const HEADER_MESSAGE = '// 🚨 Auto-generated by genSvg.js, do not edit'
    const content = exports.length === 0
        ? `${HEADER_MESSAGE}\n\nexport type tmp = never;\n`
        : `${HEADER_MESSAGE}\n\n${exports}`
    return content
}
